- id: render-manifests
  name: Render manifests
  language: script
  entry: hooks/render.py

- id: update-namespaces
  name: Update namespaces
  language: script
  entry: hooks/update_namespaces.py

- id: split-results
  name: Split results
  language: script
  entry: hooks/split_results.py
